CREATE TABLE ROLE (
	ID_ROLE INTEGER,
	ROLE VARCHAR2 (10),
	PRIMARY KEY(ID_ROLE)
);

CREATE TABLE ACCOUNTS (
	CPF VARCHAR2(11),
	NAME VARCHAR2 (50),
	EMAIL VARCHAR2 (64),
	PASSWORD VARCHAR2 (128),
	BIRTH_DATE TIMESTAMP,
	SEX VARCHAR2 (1),
	TEL VARCHAR2 (16),
	CEP VARCHAR2 (10),
	STREET VARCHAR2 (50),
	ADDRESS_NUMBER VARCHAR2 (10),
	DISTRICT VARCHAR2 (50),
	CITY VARCHAR2 (50),
	STATE VARCHAR2 (2),
	ROLE INTEGER,
	PRIMARY KEY (CPF),
	FOREIGN KEY (ROLE) REFERENCES ROLE(ID_ROLE)
);

-- Refazer tabela CATEGORY

-- Quebrado: Tabela CATEGORY não existe
CREATE TABLE BOOK (
	ISBN INTEGER,
	TITLE VARCHAR2 (50),
	AUTHOR VARCHAR2 (50),
	PUBLISHER VARCHAR2 (30),
	QUANTITY INTEGER,
	DESCRIPTION VARCHAR2 (100),
	IMG_URL VARCHAR2 (100),
	PRIMARY KEY(ISBN)
);

-- Quebrado: Tabela BOOK não foi criada, pois CATEGORY não existe
CREATE TABLE BORROWING (
	ID_BORROWING INTEGER,
	CPF VARCHAR2(11),
	ISBN INTEGER,
	PRIMARY KEY(ID_BORROWING),
	FOREIGN KEY (CPF) REFERENCES ACCOUNTS(CPF),
	FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
);