CREATE TABLE ROLE (
	ID_ROLE INTEGER,
	ROLE VARCHAR (10),
	PRIMARY KEY(ID_ROLE)
);

CREATE TABLE BOOK_STATUS (
	ID INTEGER,
	STATUS VARCHAR (10),
	PRIMARY KEY(ID)
);

CREATE TABLE ACCOUNTS (
	CPF VARCHAR(11),
	NAME VARCHAR (50),
	EMAIL VARCHAR (64),
	PASSWORD VARCHAR (128),
	BIRTH_DATE TIMESTAMP,
	SEX VARCHAR (1),
	TEL VARCHAR (16),
	CEP VARCHAR (10),
	STREET VARCHAR (50),
	ADDRESS_NUMBER VARCHAR (10),
	DISTRICT VARCHAR (50),
	CITY VARCHAR (50),
	STATE VARCHAR (2),
	ROLE INTEGER,
	PRIMARY KEY (CPF),
	FOREIGN KEY (ROLE) REFERENCES ROLE(ID_ROLE)
);

CREATE TABLE BOOK (
	ISBN INTEGER,
	CODE INTEGER,
	TITLE VARCHAR (50),
	AUTHOR VARCHAR (50),
	PUBLISHER VARCHAR (30),
	DESCRIPTION VARCHAR (100),
	IMG_URL VARCHAR (100),
	STATUS_ID INTEGER,
	PRIMARY KEY(ISBN, CODE),
	FOREIGN KEY (STATUS_ID) REFERENCES BOOK_STATUS(ID)
);

-- NEED TO BE RENAMED
CREATE TABLE BOOK_CONTROL (
	BOOK_ISBN INTEGER,
	BOOK_CODE INTEGER,
	USER_CPF VARCHAR(11),
	EXPIRE_DATE BIGINT,
	RENEWAL_NUMBER INTEGER,
	PRIMARY KEY (BOOK_ISBN, BOOK_CODE, USER_CPF),
	FOREIGN KEY (BOOK_ISBN, BOOK_CODE) REFERENCES BOOK (ISBN, CODE),
	FOREIGN KEY (USER_CPF) REFERENCES ACCOUNTS (CPF)
);


-- NOT BEING USED YET
CREATE TABLE USER_ACTION (
	ID INTEGER,
	ACTION VARCHAR (20),
	PRIMARY KEY (ID)
);

CREATE TABLE USER_ACTION_HISTORY (
	ID INTEGER,
	USER_CPF VARCHAR(11),
	BOOK_ISBN INTEGER,
	BOOK_CODE INTEGER,
	ACTION_TYPE INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_CPF) REFERENCES ACCOUNTS(CPF),
	FOREIGN KEY (BOOK_ISBN, BOOK_CODE) REFERENCES BOOK (ISBN, CODE),
	FOREIGN KEY (ACTION_TYPE) REFERENCES USER_ACTION(ID)
);