INSERT INTO ROLE(ID_ROLE, ROLE) VALUES(1, 'ADMIN');
INSERT INTO ROLE(ID_ROLE, ROLE) VALUES(2, 'USER');
INSERT INTO ROLE(ID_ROLE, ROLE) VALUES(3, 'DONOR');

INSERT INTO STATUS(ID_STATUS, STATUS) VALUES(1, 'PENDING');
INSERT INTO STATUS(ID_STATUS, STATUS) VALUES(2, 'AVAILABLE');
INSERT INTO STATUS(ID_STATUS, STATUS) VALUES(3, 'DELETED');