INSERT INTO ROLE(ID_ROLE, ROLE) VALUES(1, 'ADMIN');
INSERT INTO ROLE(ID_ROLE, ROLE) VALUES(2, 'USER');
INSERT INTO ROLE(ID_ROLE, ROLE) VALUES(3, 'DONOR');

INSERT INTO BOOK_STATUS(ID, STATUS) VALUES(1, 'PENDING');
INSERT INTO BOOK_STATUS(ID, STATUS) VALUES(2, 'AVAILABLE');
INSERT INTO BOOK_STATUS(ID, STATUS) VALUES(3, 'DELETED');
INSERT INTO BOOK_STATUS(ID, STATUS) VALUES(4, 'RESERVED');
INSERT INTO BOOK_STATUS(ID, STATUS) VALUES(5, 'BORROWED');